# .github/workflows/commitlint.yml
name: Commitlint

on:
  push:
    branches:
      - master
      - dev
      - preview

jobs:
  commitlint:
    runs-on: ubuntu-latest

    steps:
      - name: Validate Commit Message
        run: |
          COMMIT_MSG=$(git log -1 --pretty=%B)
          if ! echo "$COMMIT_MSG" | grep -qE "^(feat|fix|docs|style|refactor|test|chore): #\d+"; then
            echo "Invalid commit message format! (feat|fix|docs|style|refactor|test|chore): #xxxxx"
            exit 1
          fi
